export const CheckboxBorderColor = '#7c8ca5';
export const ButtonBorderColor = '#d3dbe6';
export const ButtonMainFontColor = '#fff';
export const ErrorColor = '#BC223E';
export const MainColor = '#5db98f';
export const Weak = '#ea753c';
export const Fair = '#e7ca27';
export const Good = '#5da3bd';
export const Strong = '#5db98f';
export const MainTextColor = '#40545E';
export const MediumGrey = '#b7bfca';
export const LightGrey = '#f6f7f9';
export const TextFieldBorderFilter =
  'invert(87%) sepia(14%) saturate(243%) hue-rotate(213deg) brightness(96%) contrast(80%)';
export const FocusColor = '#80b4ea';
export const ButtonBackground = '#4EB7A1';
export const ButtonSecondaryBackground = '#F0F3FA';
export const ButtonHoverColor = '#419a88';
export const InputText = '#252c2f';
export const ButtonBorder = '#CBC5DA';
export const Label = '#5C6889';

// My Account
export const MyAccountMainColor = '#ffffff';
export const MyAccountBlue = '#031a6e';
export const MyAccountContentColor = '#f8f9fc';
export const MyAccountTextColor = '#fff';
export const MyAccountTextDark = '#3C3C3C';
export const MyAccountTextDark2 = '#3d3d3d';
export const MyAccountTextGray = '#7B849D';
export const MyAccountTextLightGray = '#F2F5FC';
export const MyAccountTextLightGray2 = '#8e98b1';
export const MyAccountBorder = '#f2f5fc';
export const HeadingColor = '#5c6889';
export const CardEditButtonBg = '#415598';
export const CardSecondaryColor = '#182c7a';
export const CardColor = '#fff';
export const PaypalMainColor = '#61AEF0';
export const PaypalSecondaryColor = '#74B8F2';
export const MyAccountMenu = '#f2f5fc';
export const MyAccountMenuActive = '#43599c';
export const SubscriptionIconDefaultBg = '#edf8f4';
export const SubscriptionIconDefaultColor = '#9cd6c9';

export const InputBorder = '#d8ddea';
export const InputLabelColor = '#838eaa';
export const DisabledInputBg = '#F4F6FC';
export const DisabledInputColor = '#4a4f5f';
export const PaymentButtonBgn = '#00112c';
