name: Code Quality Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  quality_checks:
    name: Run Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run format check
        run: pnpm lint

      - name: Run TypeScript check
        run: pnpm ts-check

      - name: Run unit tests
        run: pnpm test-ci
