name: Prepare feature package

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  publish:
    uses: ./.github/workflows/call-publish.yml
    permissions:
      contents: read
      packages: write
    with:
      access: restricted
      registry: npm.pkg.github.com
      scope: '@cleeng'
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
