name: Publish library on npm registry

on:
  release:
    types: [created]

jobs:
  publish:
    uses: ./.github/workflows/call-publish.yml
    permissions:
      contents: read
      packages: write
    with:
      access: public
      registry: registry.npmjs.org
    secrets:
      TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
