name: pushbot test

on:
  workflow_call:

jobs:
  merge_main_to_develop:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup
        with:
          composer-args: '--no-dev'

      - uses: Cleeng/actions/setup-git@main
        with:
          APP_ID: ${{ secrets.PUSHBOT_APP_ID }}
          PRIVATE_KEY: ${{ secrets.PUSHBOT_PRIVATE_KEY }}

      - name: Merge main into develop
        run: |
          git fetch origin develop
          git fetch origin main
          git checkout develop
          git merge --no-ff origin/main
          git push origin develop
