name: Prepare restricted testing feature package - React 16

on:
  push:
    branches:
      - 'chore/MSSDK-1787-react-16-private-publish-script'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'react-16-temporary-support'

jobs:
  publish:
    uses: ./.github/workflows/call-publish.yml
    permissions:
      contents: read
      packages: write
    with:
      access: restricted
      registry: npm.pkg.github.com
      scope: '@cleeng'
      # branch: ${{ github.event.inputs.branch }}
      branch: 'chore/MSSDK-1787-react-16-private-publish-script'
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
