name: Prepare feature package - React 16

on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'react-16-temporary-support'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: ./.github/workflows/call-publish.yml
        with:
          access: restricted
          registry: npm.pkg.github.com
          scope: '@cleeng'
          branch: ${{ github.head_ref }}
