name: Prepare restricted testing feature package - React 16

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'react-16-temporary-support'

jobs:
  publish:
    uses: ./.github/workflows/call-publish.yml
    permissions:
      contents: read
      packages: write
    with:
      access: restricted
      registry: npm.pkg.github.com
      scope: '@cleeng'
      branch: ${{ github.event.inputs.branch }}
    secrets:
      TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
