name: Prepare feature package - React 16

on:
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/call-publish.yml
    permissions:
      contents: read
      packages: write
    with:
      access: restricted
      registry: npm.pkg.github.com
      scope: '@cleeng'
      branch: ${{ github.head_ref }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
