name: Publish library on npm registry

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: patch sdk version
        run: >
          sed -i
          "s/0.0.0-development/${{ github.event.release.tag_name }}/"
          package.json

      - name: install deps
        run: npm ci

      - name: compile the bundle
        run: npm run compile

      - name: push the bundle to registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
